title: Brooklyn Bridge Field Exploration
description: Anthony Tommaso; Computer Science Major - Hunter College - The City University of New York
Welcome to my post about Pier 5 in Brooklyn Bridge Park.  
Below is a quick Table of Contents so you can jump to sections you find most interesting.

## Table of Contents
- [Arriving @ the Park](#arriving--the-park)
- [Scenic Shoreline Views](#scenic-shoreline-views)
- [The Soccer Field](#the-soccer-field)
- [Conclusion](#conclusion)

theme: jekyll-theme-minimal
